/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutLoginRouteImport } from './routes/_layout/login'
import { Route as LayoutAuthedRouteImport } from './routes/_layout/_authed'
import { Route as LayoutOauthCallbackRouteImport } from './routes/_layout/oauth/callback'
import { Route as LayoutAuthedHomeIndexRouteImport } from './routes/_layout/_authed/home/index'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLoginRoute = LayoutLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAuthedRoute = LayoutAuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOauthCallbackRoute = LayoutOauthCallbackRouteImport.update({
  id: '/oauth/callback',
  path: '/oauth/callback',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAuthedHomeIndexRoute = LayoutAuthedHomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => LayoutAuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LayoutLoginRoute
  '/oauth/callback': typeof LayoutOauthCallbackRoute
  '/home/': typeof LayoutAuthedHomeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof LayoutIndexRoute
  '/login': typeof LayoutLoginRoute
  '/oauth/callback': typeof LayoutOauthCallbackRoute
  '/home': typeof LayoutAuthedHomeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/_authed': typeof LayoutAuthedRouteWithChildren
  '/_layout/login': typeof LayoutLoginRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/oauth/callback': typeof LayoutOauthCallbackRoute
  '/_layout/_authed/home/': typeof LayoutAuthedHomeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/oauth/callback' | '/home/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/oauth/callback' | '/home'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/_authed'
    | '/_layout/login'
    | '/_layout/'
    | '/_layout/oauth/callback'
    | '/_layout/_authed/home/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/login': {
      id: '/_layout/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LayoutLoginRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_authed': {
      id: '/_layout/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutAuthedRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/oauth/callback': {
      id: '/_layout/oauth/callback'
      path: '/oauth/callback'
      fullPath: '/oauth/callback'
      preLoaderRoute: typeof LayoutOauthCallbackRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_authed/home/': {
      id: '/_layout/_authed/home/'
      path: '/home'
      fullPath: '/home/'
      preLoaderRoute: typeof LayoutAuthedHomeIndexRouteImport
      parentRoute: typeof LayoutAuthedRoute
    }
  }
}

interface LayoutAuthedRouteChildren {
  LayoutAuthedHomeIndexRoute: typeof LayoutAuthedHomeIndexRoute
}

const LayoutAuthedRouteChildren: LayoutAuthedRouteChildren = {
  LayoutAuthedHomeIndexRoute: LayoutAuthedHomeIndexRoute,
}

const LayoutAuthedRouteWithChildren = LayoutAuthedRoute._addFileChildren(
  LayoutAuthedRouteChildren,
)

interface LayoutRouteChildren {
  LayoutAuthedRoute: typeof LayoutAuthedRouteWithChildren
  LayoutLoginRoute: typeof LayoutLoginRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutOauthCallbackRoute: typeof LayoutOauthCallbackRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAuthedRoute: LayoutAuthedRouteWithChildren,
  LayoutLoginRoute: LayoutLoginRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutOauthCallbackRoute: LayoutOauthCallbackRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
